### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by zudov**
This `ol'` word clearly looks as a typo. I am not sure if `old` was intended meaning, but it seem to match. Correct me if I guessed it wrong.

### CODE REVIEW

**Comment by zudov** [comment]
If it's not a typo and `ol'` carries some meaning it probably worth to explain it.

**Comment by getify** [comment]
it's American slang to abbreviate **old** to **ol'**, mostly for a folksy or informal tone. It's often used in phrases like "good ol' time" or "my ol' man" (my father).

Agreed it's not the easiest to google search for unless you know what to look for already. Not sure it matters too much. But saying "any old function" sounds wrong to American *ears*, so if it's going to be fixed, the word should just be dropped altogether.

**Comment by zudov** [comment]
@getify Oh. I see, it's my confusion after all. Thanks for explanation.

Considering this detail I think it would be better to leave it as it is.

**Comment by getify** [comment]
Cheers!

**Pull request closed without merging**
