### PR TITLE
修复链接错误使用中文括号问题

### PR DESCRIPTION
**Pull request by hijiangtao**

### CODE REVIEW

**Comment by JoeHetfield** [comment]
The original text: 

>  One such polyfill is "Native Promise Only" (http://github.com/getify/native-promise-only), which I wrote!

It seems  the author didn't mean to mark this part as an link but as plain text, so I think we should follow his mind.

**Comment by JoeHetfield** [comment]
Ah, just like your another PR, the double-byte parentheses was a mistake indeed.

**Comment by hijiangtao** [comment]
Well, it seems I did a wrong modification, but it also needs another PR to fix its link mixed with both url and its followed chinese characters.

**Comment by JoeHetfield** [comment]
Reopened, you can use this PR

**Comment by JoeHetfield** [comment]
Use single-byte parentheses man, not add the new angle brackets

**Comment by hijiangtao** [comment]
I don't know what you really want to express? Single-byte parentheses will not separate words exactly, such as "我写的！" with its previous sentence, just like below:

image

But only angle bracket can make a proper link without title set to it. I think the problem is to fix the impropriate linking, rather than replace the double-byte parentheses (in chinese version).

**Comment by JoeHetfield** [comment]
OK，I got you, I think this is the way that github interpret  markdown. I tried single-byte parentheses on VSCode, it display properly：
image
so, how about just leave it, cause every similar places gonna have this issue, I will fix them when I found a better way.

**Comment by hijiangtao** [comment]
Yes, it really does. I think it's VSCode that help fix the display problem instead, because everything followed by a url without space should be thought to a part of url itself. Similar problems occured in some other places, hope you get a better hint and "fix" them. Thank you.

**Pull request closed without merging**
