### PR TITLE
Typo correction

### PR DESCRIPTION
**Pull request by alisterlf**
Changing
this
(`a > 41` here)
to this
(`a > 41`) here

### CODE REVIEW

**Comment by getify** [comment]
I don't think your change makes the text more clear, but instead I think it ever so slightly makes it less clear. Can you explain your reasoning?

**Comment by huei90** [comment]
Why don't just remove the word `here`?

**Comment by alisterlf** [comment]
When I read it, I thought it was is a typo the `here` being inside the expression.
For this reason I just moved the word out of expression.
But I agree with @huei90 , the word "here" can be removed.

**Comment by getify** [comment]
Doesn't seem like a justified change, so closing for now. If there's further discussion to be had, please feel free to re-address.

**Pull request closed without merging**
