### PR TITLE
Easily movable table of contents to up&going

### PR DESCRIPTION
**Pull request by uppusaikiran**
When i was going to readme.md file,because it is so large i often lost where iam presently there.So entire chapter into several sub modules and these sub modules are listed as table of contents and links to appropriate sub modules are added.

### CODE REVIEW

**Comment by kevcomedia** [comment]
I'm also thinking that a small table of contents in each chapter would be useful, since a chapter can be fairly long.

**Comment by kevcomedia** [comment]
Hi again. I saw your changes and noticed that you used absolute URLs in the links. In my opinion a relative URL is a better choice.

**Comment by uppusaikiran** [comment]
Thanks for suggestion , iam awaiting response from owner.Because he might be in another idea.

**Comment by getify** [comment]
The primary intent of this repo is to maintain the text so that it can be imported by the book publisher and produced. I do not arrange it or add content here which is not appropriate for that task because then it's a lot of manual error-prone work to filter it out whenever they import.

**Pull request closed without merging**
