### PR TITLE
Update ch1.md

### PR DESCRIPTION
**Pull request by MehdiRaash**
More cleaner.

### CODE REVIEW

**Comment by getify** [comment]
I like `==`, especially since in this case it would allow either `undefined` or `null` depending on preference. I don't see this change improving anything.

**Comment by MehdiRaash** [comment]
I just changed the form because:
In one of your books you gave a very nice and deep explanation to users about the **types**, I merely feel that it repeats (what you taught before and emphasise on them) that **undefined** is a type here implicitly not a string.
Thank you for the consideration.

**Comment by getify** [comment]
The context of the example is that `a` is either `undefined` or it gets set to some number. No number is ever `==` (coercively equal) to `undefined`, so the `==` isn't any danger here. I tend to prefer the shorter form when it's safe, and it seems safe here.

Moreover, if someone later decided they didn't want just `var a;` but rather `var a = null;`, then the `== undefined` check actually has the benefit of `null` and `undefined` being coercively equal. So, in a way, it sorta future proofs to that case.

**Comment by MehdiRaash** [comment]
Okay, "future proofs" as you said...
Mr Simpson, I know it's not a good place to say but It's about a while I have asked this question but no answer I got till now.
Would you please take a look [at this](http://stackoverflow.com/questions/40073278/google-chromes-unpredictable-behaviour-on-alert-function) question. I'm confused.

**Comment by getify** [comment]
Posted a comment there. :)

**Pull request closed without merging**
