### PR TITLE
Typo where I writeable should be true

### PR DESCRIPTION
**Pull request by deepakcdo**
Typo where I writeable should be true as it says 'it's not marked as read-only '

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

### CODE REVIEW

**Comment by getify** [comment]
Please search existing issues before filing.

**Comment by deepakcdo** [comment]
I checked master before proposing this change.

Its difficult to check all the issues. If this has been reported and you agree this is an error how come the merge request was not accpected so mater is updated. 

If the errors are not merged into master then there is no point me providing my corrections.

**Comment by getify** [comment]
> Its difficult to check all the issues

When you file a PR/issue there is a link to the contribution guidelines, which you had to remove as you were filing, indicating you read them. They explain, among other things, that it's better to search first, then file an issue, then file a PR last.

If you search for "writable", you'll find a dozen issues.

> how come the merge request was not accpected so mater is updated

First, I don't fully agree with the change, as is discussed in the various previous issues.

Second, this is a published book and I'm keeping master the same as the published 1st edition.

Also if you search there are over 100 issues (including writable) that are labeled "second edition". That work has not started yet (it's a lot to do, and there are some complications) so that's why that label is tracking all those issues.

Once second edition starts, master will be second edition and first edition will move to a branch.

**Comment by deepakcdo** [comment]
Thanks for the note. 

Since most readers will read the book and want to check the errors quickly, is it worth having a branch which is the start of the second verison?  This is common practice for developers and will see what you are trying to achieve. 

So master can remain as you like ( published book).  

After searching for writeable like you suggested its clear many people are confused. So the second branch with some curicial fixes will help.

**Pull request closed without merging**
