### PR TITLE
Edits preface to be more concise and precise - less long sentences, f…

### PR DESCRIPTION
**Pull request by seanohue**
…ixes some punctuation, and uses more precise verbage and less adverbs.

### CODE REVIEW

**Comment by seanohue** [comment]
Credentials: former English major and teacher :)

**Comment by getify** [comment]
I appreciate the edits, but I'm not going to merge this for now. The preface is the same across all 6 books (5 of which are already long-since published). I don't want to have different versions of it.

So, when I get to the second edition of the books, I'll come back and pull in these changes.

Thanks!

**Comment by seanohue** [comment]
No problem, that makes sense. I'm going to go through and make edits on some of the other chapters. I saw in one of the issues you were considering hiring(?) an editor but hopefully I can save you some money or time. :+1:

**Comment by getify** [comment]
> considering hiring(?) an editor

These books are all being edited and published by O'Reilly. They have staff for copy-editing, general editorial, tech editorial, etc. They also bring in specific domain experts to provide feedback.

In addition to what O'Reilly does for editing the books, I'm also grateful to those who contribute from the community. That's the primary reason this is all in the open on GH. :)

**Comment by seanohue** [comment]
Ah, good to know.

**Comment by getify** [comment]
Just keep in mind: the first five books have already been published, and the sixth (final) one is heading to production soon.

A round of second editions is extremely likely for all the books, but PRs for changes (beyond errata fixes like typos) made at this point may go un-merged for awhile, and may in fact be end up bit-rotting as the edits on the second editions start up later in the summer.

Thanks!

**Comment by seanohue** [comment]
Okay, that's fine. I do have to make open-source contributions as a requirement for a program I am in, but I do hope you use some of the changes. Have a great day!

**Comment by getify** [comment]
I will use as many of them as I can, and they're much appreciated! Just wanted to make sure to explain expectations of timing. :)

**Comment by getify** [comment]
Closing as not applicable anymore, since the 2nd-ed has a rewritten preface.

**Pull request closed without merging**
