### PR TITLE
Eval is maligned (and rightly so), and punctuation goes inside quotes.

### PR DESCRIPTION
**Pull request by morganestes**
This just caught my eye while browsing the chapter. Looking forward to getting to read more of it soon.

### CODE REVIEW

**Comment by mallowigi** [comment]
Why is punctuation inside quotes? Doesn't feel right to me.

**Comment by getify** [comment]
I dunno @morganestes motivation, but it's that way to comply with O'Reilly publishing style. I believe it's pretty commonly accepted in publishing.

**Comment by bmacdonald-oreilly** [comment]
Editor here: It's not a publishing convention, it's an English language convention, at least in American English. UK English does it differently:
http://grammar.ccc.commnet.edu/grammar/marks/quotation.htm
Obviously, that means it's an arbitrary convention, but American publishers follow American English rules.

**Comment by morganestes** [comment]
@mallowigi and @getify: 
My changes were suggested based on years of editing to various writing styles, but most recently from the Associated Press and Yahoo! Style Guides. I realize it's subjective as American and UK English follow different rules, and the book is available worldwide, but since it's an American publisher I went with American rules of [periods and commas inside the quotes](https://owl.english.purdue.edu/owl/resource/735/02/).

**Pull request merged**
