### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by EstebanMarin**
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

### CODE REVIEW

**Comment by EstebanMarin** [comment]
@getify This is the initial translation for spanish. Should we leave a Spanish branch?

**Comment by EstebanMarin** [comment]
@getify I made a PR to master to setup the workflow of the translation before moving into bigger chucks of work. I have people interested in this so would be great to clear this details before adding more people too. 
thanks again!

**Comment by getify** [comment]
The PR looks good. But I don't want to create the branch and merge chunk by chunk, because that makes the main repo very noisy while translations (especially multiple ones) are being worked on.

What worked well on the official Chinese translation was that the entire translation was managed in their own repo. Once they felt they were substantially done (with all 6 books), they made one PR to a new branch (that I created for them) and we added all the translation work. At that point, I promoted Joe to a repo maintainer so he could further manage that translation's branch from that point forward.

That strategy minimizes the noise on the repo during the churn of translations, with only the (hopefully much less) noise of maintenance of translations hitting the main repo.

I would be willing to add one book at a time to the main repo, if it was really desired to go book-by-book, but for the stated reasons of minimizing the issue-traffic on this repo, I don't want to add chapter-by-chapter.

----

I understand why you're wanting to work out workflow. I get that.

I would say the simplest thing is to establish what workflows work best for you, on your own repo. I don't have any opinion on how you want to manage the translation process. That should be up to you!

That's why deferring the merging to the main repo branch until "the end" frees you up from concerns about workflow.

Once you have a book (or all six books) ready to merge, there's a dramatically simpler workflow involved:

1. File an issue asking for the branch, named for the official language of the translation.

2. Once that branch is created, file a single rolled-up PR to that branch.

3. Once I merge that, I will promote you to repo maintainer so that you can manage all further translation work on that branch (including triaging any issues that come into the main repo).

4. Ideally, at that point, no further work is going on in your original repo. Think of your repo as a staging ground to work out all the translation stuff, and then merging as the "end" of that staging environment.

Does that help clarify workflow?

**Comment by EstebanMarin** [comment]
Absolutely. I understand now the reason why having multiple commits to the man repo can be painfull and noisy, and having my own repo as a staging environment would be the best, that way I can optimze workflow without getting you involved in the needy greedy. 

I will then:

1. Rename the PR so anyone interested can find this thread.

2. Leave the issue [1377](https://github.com/getify/You-Dont-Know-JS/issues/1377), also for the same reasons above.

3. I will leave in these Thread, PR, and ISSUE, link to the staging repo. That way we do not loose any possible contributors. 

Without further ado, I will PR per book (for the moment).

**Comment by EstebanMarin** [comment]
### Spanish Translation Repo: 
[Translation Staging fork](https://github.com/EstebanMarin/You-Dont-Know-JS) 
Note: Though it is a personal repo as discussed with @getify [here](https://github.com/getify/You-Dont-Know-JS/pull/1378) this is the best approch. Also, all contributors will be mentioned and added in the Per Chapter PR.

**Comment by camilomontoyau** [comment]
@EstebanMarin gotcha
@getify thanks for taking the time to answer

**Comment by camilomontoyau** [comment]
@EstebanMarin do you want to have a talk before starting? 
btw, I'm from Colombia and camilomontoya2@gmail.com is my e-mail

**Comment by Zenfeuer** [comment]
Hi all.

Also I would like to collaborate, actually Im working on my own documentation of Javascript (https://github.com/Zenfeuer/Weird-Javascript) and can help to translate this to spanish :).

**Comment by EstebanMarin** [comment]
@Zenfeuer Many thanks. I noticed that the link was pointing to an old Repo. I move the translation into an own organization rather than a a personal repo. That way people can get more engaged into the process. https://github.com/You-Dont-Know-JS-ES/Traduccion
(here)[https://github.com/You-Dont-Know-JS-ES/Traduccion]
I also archived the old one, and updated the readme. Thanks for that and keen to see a lot of PRs from your end!

**Comment by Zenfeuer** [comment]
Cool @EstebanMarin ! I'm going to use the new repo then 👍

**Comment by gerardolgvr** [comment]
@EstebanMarin  I would like to help to translate the books. Can I use the new repo you created?

**Comment by horacioh** [comment]
hello folks!!

where can I see the progress on this issue? is there another repo link I can go and see the current status?

thanks!

**Pull request closed without merging**
