### PR TITLE
To many parenthesis

### PR DESCRIPTION
**Pull request by sherrygirl30**
[**Yes,]([url](`url`)) I promise I've read # **the**  [#**_[Contributions_**]( @regularmike 

- [ ]  **#@**

> )

 Guidelines](CONTRIBUTING.md)** (please feel free to remove this line).

### CODE REVIEW

**Comment by legodude17** [comment]
What is this for @sherrygirl30?

**Comment by edg2s** [comment]
To**o** many parenthes**e**s

**Comment by legodude17** [comment]
I know, but the files changed have nothing to do with that, and they just included commits form other PRs.

**Comment by chimywang** [comment]
44

**Comment by chimywang** [comment]
1

**Pull request closed without merging**
