### PR TITLE
Update ch3.md

### PR DESCRIPTION
**Pull request by hijiangtao**
链接被延长排版

### CODE REVIEW

**Comment by JoeHetfield** [comment]
Thanks for your help, but I think the true suspects are the double-byte parentheses. pls PR again if you fixed it

**Comment by hijiangtao** [comment]
Well, I don't think this is the author's original idea, check the screenshots as below:

image

image

**Comment by JoeHetfield** [comment]
Yes, the double-byte parentheses was a mistake, I should use the single-byte parentheses.

**Comment by hijiangtao** [comment]
A same problem with #1119

**Pull request closed without merging**
